# Generated by Django 5.2 on 2025-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('remote_support', models.BooleanField(default=False)),
                ('adaptive_support', models.BooleanField(default=False)),
                ('test_type', models.JSONField()),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
