# Generated by Django 5.2 on 2025-04-08 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirely', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
